[project]
name = "orange"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "orange3",
    "pyqt6>=6.10.1",
    "pyqt6-webengine>=6.10.0",
]
